### ISSUE TITLE
Remove all traces of registry signatures

### ISSUE THREAD

**Issue by sokorototo** [zeskeertwee/virtfs-rs#10]
It's that easy we discussed it on Discord

**Comment by zeskeertwee** [comment]
I just realized that this would allow paths to be altered, without it being known. Do we still want this @sokorototo?

**Comment by zeskeertwee** [comment]
what i meant is someone could swap 2 paths, thus the wrong file is loaded but no errors appear at all.

**Comment by sokorototo** [comment]
That is a problem, but the implementation is too much of a hassle. It requires that you know the size of the data in the registry, which due to the whole "dynamic" entry size thing requires that you read all entries. This is slow, plus it is a problem that even OS filesystems have, if you change the names of files, then the applications needing those files _will_ break. We sure can prevent it by hashing the registry, but God does it make the code innefficient.

**Comment by zeskeertwee** [comment]
Yeah It definitely adds complexity, but since it's already implemented right now and it doesn't actually add that much of an overhead, why not leave it in?
(I also like a challenge every now and then :) )

**Comment by sokorototo** [comment]
I already scrapped it, many commits ago on my working branch anyway, It does not just add complexity but it also requires that the whole registry be loaded into memory so that it could be signed. Easy, the registry is tiny. Right? The problem is that we can not use streams. No matter how small the reg is, it still needs to be in memory. It is really inefficient for memory. Plus, as I have said it is a serious pain in the butt to do.

**Comment by sokorototo** [comment]
@zeskeertwee I have gone for a walk and come back with a **way**, _way_, better solution. It works for both our problems too. We already have a hash for each leaf. And part of a leaf's identity is the name of its path. So we just hash the pathname into the signature, like some sort of nonce. If you query a leaf it validates both the path and the data. No need for a registry signature. It just works.

**Comment by sokorototo** [comment]
This is what I am going with, in my working branch.

**Comment by zeskeertwee** [comment]
Holy shit that's brilliant

**Comment by zeskeertwee** [comment]
So just put the path before the leaf when computing the signature?

**Comment by sokorototo** [comment]
Put the path after the leaf, so less data is moved.

**Comment by sokorototo** [comment]
So now you can close the issue as we have the solution?
